config:
  validation: true

processors:
  active: true

console-reports:
  active: true

comments:
  active: true

complexity:
  active: true
  CyclomaticComplexMethod:
    active: true
    ignoreAnnotated:
      - Composable
  ComplexCondition:
    active: true
    threshold: 4
  LargeClass:
    active: true
    threshold: 500
  LongMethod:
    active: true
    threshold: 150
    ignoreAnnotated:
      - Composable
    excludes:
      - '**/*Migration*.kt'
  LongParameterList:
    active: true
    functionThreshold: 8
    constructorThreshold: 10
  TooManyFunctions:
    active: true
    thresholdInFiles: 25
    thresholdInClasses: 25
    ignoreAnnotated:
      - Module
      - dagger.Module

coroutines:
  active: true

empty-blocks:
  active: true

exceptions:
  active: true
  TooGenericExceptionCaught:
    active: true
    excludes:
      - '**/DocumentSyncEngine.kt'

naming:
  active: true
  FunctionNaming:
    active: true
    ignoreAnnotated:
      - Composable
  TopLevelPropertyNaming:
    active: true
    constantPattern: '[A-Z][_A-Z0-9]*'

performance:
  active: true

potential-bugs:
  active: true

style:
  active: true
  ReturnCount:
    active: true
    max: 6
  ThrowsCount:
    active: true
    max: 5
  MagicNumber:
    active: true
    ignorePropertyDeclaration: true
    ignoreAnnotated:
      - Composable
      - Preview
    ignoreNumbers:
      - '-1'
      - '0'
      - '1'
      - '2'
      - '8'
      - '401'
      - '403'
      - '404'
      - '408'
      - '429'
    excludes:
      - '**/ReaderThemeColors.kt'
      - '**/theme/**'
  MaxLineLength:
    active: true
    maxLineLength: 120
    excludePackageStatements: true
    excludeImportStatements: true
  WildcardImport:
    active: true
    excludeImports:
      - 'kotlinx.coroutines.*'
