config:
  validation: true

processors:
  active: true

console-reports:
  active: true

ktlint:
  active: true
  autoCorrect: false

comments:
  active: true

complexity:
  active: true
  LongMethod:
    active: true
    allowedLines: 150
    ignoreAnnotated:
      - Composable
    excludes:
      - '**/*Migration*.kt'
  LongParameterList:
    active: true
    allowedFunctionParameters: 8
    allowedConstructorParameters: 10
  TooManyFunctions:
    active: true
    allowedFunctionsPerFile: 25
    allowedFunctionsPerClass: 25
    ignoreAnnotated:
      - Module
      - dagger.Module

coroutines:
  active: true

empty-blocks:
  active: true

exceptions:
  active: true

naming:
  active: true
  FunctionNaming:
    active: true
    ignoreAnnotated:
      - Composable
  TopLevelPropertyNaming:
    active: true
    constantPattern: '[A-Z][_A-Z0-9]*'

performance:
  active: true

potential-bugs:
  active: true

style:
  active: true
  MagicNumber:
    active: true
    ignorePropertyDeclaration: true
    ignoreAnnotated:
      - Composable
      - Preview
    ignoreNumbers:
      - '-1'
      - '0'
      - '1'
      - '2'
      - '8'
      - '401'
      - '403'
      - '404'
      - '408'
      - '429'
    excludes:
      - '**/ReaderThemeColors.kt'
      - '**/theme/**'
  MaxLineLength:
    active: true
    maxLineLength: 120
    excludePackageStatements: true
    excludeImportStatements: true
  WildcardImport:
    active: true
    excludeImports:
      - 'kotlinx.coroutines.*'
