config:
  validation: true

processors:
  active: true

console-reports:
  active: true

comments:
  active: true

complexity:
  active: true
  LongMethod:
    active: true
    allowedLines: 80
  LongParameterList:
    active: true
    allowedFunctionParameters: 8
    allowedConstructorParameters: 10
  TooManyFunctions:
    active: true
    allowedFunctionsPerFile: 20
    allowedFunctionsPerClass: 20

coroutines:
  active: true

empty-blocks:
  active: true

exceptions:
  active: true

naming:
  active: true
  FunctionNaming:
    active: true
    ignoreAnnotated:
      - Composable
  TopLevelPropertyNaming:
    active: true
    constantPattern: '[A-Z][_A-Z0-9]*'

performance:
  active: true

potential-bugs:
  active: true

style:
  active: true
  MagicNumber:
    active: true
    ignorePropertyDeclaration: true
    ignoreAnnotated:
      - Composable
      - Preview
  MaxLineLength:
    active: true
    maxLineLength: 120
    excludePackageStatements: true
    excludeImportStatements: true
  WildcardImport:
    active: true
    excludeImports:
      - 'kotlinx.coroutines.*'
